import json
import os
import secrets
import time

from google import genai
from google.genai import types
from loguru import logger
from omegaconf import DictConfig

from topreward.mapper.base import BaseMapper
from topreward.utils.errors import PercentagesNormalizationError


class GeminiMapper(BaseMapper):
    def __init__(
        self,
        model_name: str = "gemini-2.5-flash-lite",
        max_new_tokens: int = 1024,
        temperature: float = 0.5,
        retries: int = 3,
        mapping_prompt: str | DictConfig = "",
    ):
        super().__init__()
        self.model_name = model_name
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
        self.retries = retries
        if isinstance(mapping_prompt, DictConfig):
            self.mapping_prompt: str = str(mapping_prompt.get("template", ""))
        else:
            self.mapping_prompt = mapping_prompt

    def extract_percentages(self, model_response: str) -> list[float]:
        """
        Uses the Google GenAI API to extract percentages and validates the list length.

        Args:
            model_response: The text generated by a model to be processed.

        Returns:
            A list of extracted percentages as floats.
        """
        local_retries = self.retries
        for attempt in range(local_retries):
            try:
                response = self.client.models.generate_content(
                    model=self.model_name,
                    config=types.GenerateContentConfig(
                        system_instruction=self.mapping_prompt,
                        temperature=self.temperature,
                        max_output_tokens=self.max_new_tokens,
                    ),
                    contents=model_response,
                )

                response_content = response.text

                if response_content is None:
                    raise ValueError("Gemini returned empty response text")

                if "```json\n" in response_content:
                    response_content = response_content.split("```json\n")[1]
                if "\n```" in response_content:
                    response_content = response_content.split("\n```")[0]

                json_response = json.loads(response_content)
                logger.debug(f"Gemini extraction response: {json_response}")
                prediction = json_response.get("prediction", [])

                return prediction

            except Exception as e:
                # Retry with exponential backoff for transient service issues (e.g. 503).
                msg = str(e).lower()
                transient = any(s in msg for s in ("503", "service unavailable", "temporarily unavailable", "429", "rate", "deadline", "timeout", "connection"))

                if attempt < local_retries - 1 and transient:
                    sleep_s = min(30.0, 1.0 * (2**attempt))
                    jitter = 0.8 + 0.4 * (secrets.randbelow(10_000) / 10_000)
                    sleep_s = sleep_s * jitter
                    logger.warning("GeminiMapper transient error (attempt {}/{}), retrying in {:.1f}s: {}", attempt + 1, local_retries, sleep_s, repr(e))
                    time.sleep(sleep_s)
                    continue

                logger.error("GeminiMapper failed to extract percentages: {}", repr(e))
                raise PercentagesNormalizationError from None

        raise PercentagesNormalizationError
